package scanner

// The positive fixtures below carry `abcd-lint:allow`, the line-scoped escape
// this class's own findings teach. They cannot use a reserved documentation host
// instead: hasReservedDocHost would then suppress the very detection each case
// asserts. The hosts and ids are synthetic — no real session is named — and the
// waiver is the honest way to say a line is deliberately illustrative.

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// TestHarnessSessionURLDetected: a live session URL is caught wherever it sits,
// which is the point — the harness appends it outside the model's own text, so
// origin cannot be a condition of detection.
func TestHarnessSessionURLDetected(t *testing.T) {
	for _, line := range []string{
		"https://agent-host.dev/code/session_01Gy4Zo93PdMmggA8sfGyb",                  // abcd-lint:allow
		"See https://agent-host.dev/code/session_01Gy4Zo93PdMmggA8sfGyb for the run.", // abcd-lint:allow
		"- Session: https://agent-host.dev/s/session-01Gy4Zo93PdMmggA8sfGyb",          // abcd-lint:allow
		// The UUID and lower-case-hex spellings a harness also mints.
		"https://agent-host.dev/code/session/8f14e45f-ceea-167a-5a36-dedd4bea2543", // abcd-lint:allow
		"https://agent-host.dev/code/session_a3f9c2d1e0b8f7a64c5d",                 // abcd-lint:allow
	} {
		if !hasKind(scanLine(line), kindHarnessSessionURL) {
			t.Errorf("session URL not detected in %q", line)
		}
	}
}

// TestHarnessSessionURLSpares an ordinary product URL and a reserved
// documentation host: the first carries no session segment, the second is
// illustrative by convention (the same allowlist-inversion the network patterns
// rest on).
func TestHarnessSessionURLSpares(t *testing.T) {
	for _, line := range []string{
		"The plugin installs from https://agent-host.dev/agent-cli today.",
		"A session URL looks like https://example.invalid/code/session_01Gy4Zo93PdMmggA8sfGyb",
		"Sessions are stored under .abcd/history/sessions/ per root_commit.",
		// A documentation URL whose slug follows the word "session" with ordinary
		// hyphenated English. Structurally identical to a session link; not one.
		// It is in this repository's own research notes.
		"[Session management and 1M context](https://agent-host.dev/blog/using-agent-session-management-and-1m-context)",
		"https://agent-host.dev/docs/session-configuration-options",
	} {
		if hasKind(scanLine(line), kindHarnessSessionURL) {
			t.Errorf("false positive on %q", line)
		}
	}
}

// TestHarnessFooterDetected covers the emphasis and emoji spellings the append
// actually lands in — the shapes scripts/check-attribution.sh was widened to
// after each got through it.
func TestHarnessFooterDetected(t *testing.T) {
	for _, line := range []string{
		"Generated with [Some Tool](https://tool.dev)",
		"🤖 Generated with [Some Tool](https://tool.dev)",
		"_Generated with [Some Tool](https://tool.dev)_",
		"🤖 _Generated with [Some Tool](https://tool.dev)_",
		"**Generated by [Some Tool](https://tool.dev)**",
		"  Generated with [Some Tool](https://tool.dev)",
	} {
		if !hasKind(scanLine(line), kindHarnessFooter) {
			t.Errorf("footer not detected in %q", line)
		}
	}
}

// TestHarnessFooterSparesProseAndExamples is the writable-about property the
// shell gate's line anchor already carries: a real footer occupies its own line,
// while prose ABOUT the ban quotes it mid-sentence, a bullet describes it, and an
// example points at a reserved documentation host. All three must survive, or
// this repo cannot document its own rule.
func TestHarnessFooterSparesProseAndExamples(t *testing.T) {
	for _, line := range []string{
		"We ban the \"Generated with [tool](url)\" footer in public text.",
		// A bullet is no longer an excuse on its own — a model-authored footer
		// lands in one — so documentation of the ban points its OWN link at a
		// reserved documentation host, which is what this repository's corpus does.
		"- Generated with [Some Tool](https://example.invalid) is refused.",
		"a single group in one position is exactly the gap that let `🤖 _Generated with [` through",
		"Generated with [Some Tool](https://example.invalid)",
		"The changelog is generated with [the derived cut] rather than by hand.",
	} {
		if hasKind(scanLine(line), kindHarnessFooter) {
			t.Errorf("false positive on %q", line)
		}
	}
}

// TestHarnessLeakPatternsAreInTheCanonicalSet pins the one-definition property:
// the class is declared once and folded into DefaultPatterns, so the four
// store-before-commit consumers, audit, docs-lint and the outbound scan all read
// the same definition rather than drifting copies.
func TestHarnessLeakPatternsAreInTheCanonicalSet(t *testing.T) {
	inDefault := map[string]bool{}
	for _, p := range DefaultPatterns() {
		inDefault[p.Kind] = true
	}
	for _, p := range HarnessLeakPatterns() {
		if !inDefault[p.Kind] {
			t.Errorf("harness-leak kind %q is missing from DefaultPatterns", p.Kind)
		}
		if !IsHarnessLeakKind(p.Kind) {
			t.Errorf("IsHarnessLeakKind does not recognise its own kind %q", p.Kind)
		}
	}
	if len(HarnessLeakPatterns()) != 2 {
		t.Errorf("expected exactly the two leak shapes, got %d", len(HarnessLeakPatterns()))
	}
}

// TestScrubOutboundStripsFooterKeepsTrailer is the outbound criterion: a PR body
// carrying the harness-appended footer comes back carrying only the repo's own
// attribution trailer.
func TestScrubOutboundStripsFooterKeepsTrailer(t *testing.T) {
	body := "Fixes the walk.\n\nAssisted-by: Claude:some-model\n\n🤖 _Generated with [Some Tool](https://tool.dev)_\n"

	got, findings, err := ScrubOutbound(t.TempDir(), body, "pr-body")
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(got, "Generated with") {
		t.Errorf("footer survived the scrub: %q", got)
	}
	if !strings.Contains(got, "Assisted-by: Claude:some-model") {
		t.Errorf("the repo's own attribution was lost: %q", got)
	}
	if len(findings) == 0 {
		t.Error("expected the scrub to report what it removed")
	}
}

// TestScrubOutboundCatchesSessionURL: an issue comment carrying a live session
// URL is caught and the URL does not survive.
func TestScrubOutboundCatchesSessionURL(t *testing.T) {
	comment := "Done — see https://agent-host.dev/code/session_01Gy4Zo93PdMmggA8sfGyb\n" // abcd-lint:allow

	got, findings, err := ScrubOutbound(t.TempDir(), comment, "issue-comment")
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(got, "session_01Gy4Zo93PdMmggA8sfGyb") {
		t.Errorf("session URL survived the scrub: %q", got)
	}
	if len(findings) == 0 {
		t.Error("expected the session URL to be reported")
	}
}

// TestScrubOutboundPassesCleanTextUnchanged: an artefact with nothing to strip
// comes back byte-identical, with no finding.
func TestScrubOutboundPassesCleanTextUnchanged(t *testing.T) {
	body := "Fixes the walk over the record stores.\n\nAssisted-by: None\n"

	got, findings, err := ScrubOutbound(t.TempDir(), body, "pr-body")
	if err != nil {
		t.Fatal(err)
	}
	if got != body {
		t.Errorf("clean text was rewritten:\n got %q\nwant %q", got, body)
	}
	if len(findings) != 0 {
		t.Errorf("expected no findings on clean text, got %+v", findings)
	}
}

// TestOutboundPolicyStatesBothHalves pins the policy an autonomous routine's
// prompt carries: the ban on session URLs and harness footers in public text,
// AND the post-create re-read-and-strip, which is the half that matters because
// the append happens outside the model's own output.
func TestOutboundPolicyStatesBothHalves(t *testing.T) {
	policy := strings.ToLower(OutboundPolicy)
	for _, want := range []string{"session url", "footer", "re-read", "strip", "after"} {
		if !strings.Contains(policy, want) {
			t.Errorf("the outbound policy does not state %q:\n%s", want, OutboundPolicy)
		}
	}
}

// The review pass found four ways the class could be evaded or could destroy
// content. Each one is pinned here.

// A footer that lands in a bullet or inside a quoted reply is the MODEL-authored
// half of the class, and it is the half that does not arrive at column 0.
func TestHarnessFooterInListAndQuote(t *testing.T) {
	for _, line := range []string{
		"- 🤖 Generated with [Some Tool](https://tool.dev)",
		"> 🤖 Generated with [Some Tool](https://tool.dev)",
		"  * Generated by [Some Tool](https://tool.dev)",
		"1. Generated with [Some Tool](https://tool.dev)",
	} {
		if !hasKind(scanLine(line), kindHarnessFooter) {
			t.Errorf("footer not detected in %q", line)
		}
	}
}

// The reserved-documentation excuse belongs to the footer's OWN link. Reading the
// rest of the line let any later example.com link disarm a genuine footer.
func TestHarnessFooterDocHostIsScopedToItsOwnLink(t *testing.T) {
	line := "🤖 Generated with [Some Tool](https://tool.dev) — docs at https://example.com/x"
	if !hasKind(scanLine(line), kindHarnessFooter) {
		t.Errorf("an unrelated documentation link disarmed a real footer: %q", line)
	}
}

// A benign leftmost candidate must not disarm the pattern for the rest of the
// line — the shape that made the lint gate weaker than the scanner it shares a
// definition with.
func TestHarnessSessionURLSecondMatchOnALine(t *testing.T) {
	line := "docs https://agent-host.dev/blog/using-agent-session-management-and-1m " +
		"and run https://agent-host.dev/code/session_01Gy4Zo93PdMmggA8sfGyb" // abcd-lint:allow
	if !hasKind(scanLine(line), kindHarnessSessionURL) {
		t.Errorf("a skipped leftmost candidate hid a real session URL: %q", line)
	}
}

// The query-parameter and host:port spellings leak exactly as much as the path
// spelling.
func TestHarnessSessionURLQueryAndPortSpellings(t *testing.T) {
	for _, line := range []string{
		"https://agent-host.dev/code?session_id=01Gy4Zo93PdMmggA8sfGyb",   // abcd-lint:allow
		"https://agent-host.dev:8443/code/session_01Gy4Zo93PdMmggA8sfGyb", // abcd-lint:allow
	} {
		if !hasKind(scanLine(line), kindHarnessSessionURL) {
			t.Errorf("session URL not detected in %q", line)
		}
	}
}

// A degraded per-repo scanner config must REFUSE, not sanitise with a silently
// weakened pattern set — the contract every sibling write-time redactor keeps.
func TestScrubOutboundRefusesADegradedScanner(t *testing.T) {
	root := t.TempDir()
	if err := os.MkdirAll(filepath.Join(root, ".abcd", "config"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(root, ".abcd", "config", "pii.json"),
		[]byte("{ not json"), 0o644); err != nil {
		t.Fatal(err)
	}

	got, _, err := ScrubOutbound(root, "Ordinary text.\n", "pr-body")
	if err == nil {
		t.Fatalf("expected a refusal on a degraded config; got %q", got)
	}
	if got != "" {
		t.Errorf("a refusal must hand back nothing to post; got %q", got)
	}
}

// A session URL inside a sentence must not take the sentence with it. Dropping
// the line returned an EMPTY artefact for a one-line comment, which the routine
// would then post.
func TestScrubOutboundKeepsTheSentenceAroundASessionURL(t *testing.T) {
	body := "Fixes the walk. Session: https://agent-host.dev/code/session_01Gy4Zo93PdMmggA8sfGyb — see notes.\n" // abcd-lint:allow

	got, findings, err := ScrubOutbound(t.TempDir(), body, "issue-comment")
	if err != nil {
		t.Fatal(err)
	}
	if len(findings) == 0 {
		t.Fatal("expected the session URL to be reported")
	}
	if strings.Contains(got, "session_01Gy4Zo93PdMmggA8sfGyb") {
		t.Errorf("session URL survived: %q", got)
	}
	if !strings.Contains(got, "Fixes the walk.") || !strings.Contains(got, "see notes.") {
		t.Errorf("the artefact's own content was destroyed: %q", got)
	}
}
