#!/usr/bin/env bash
# Test corpus for check-attribution.sh's body check.
#
# iss-214 asked for this specifically: the regex must be proven against the
# trailer forms ACTUALLY IN USE in this repository's history, not only against
# the happy path it was written from. `git log` over the record at the time of
# writing shows claude-fable-5 (256), claude-opus-4-8 (225), claude-opus-5 (123),
# claude-opus-5[1m] (33), claude-sonnet-5 (12) and claude-opus-4-8[1m] (5) — the
# bracketed context-window forms are ordinary history, and the first cut of the
# gate rejected every one of them.
#
# Run: bash scripts/check-attribution-cases.sh   (exit 0 all pass, 1 otherwise)
set -uo pipefail
cd "$(git rev-parse --show-toplevel)"

SCRIPT=scripts/check-attribution.sh
tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

pass=0
fail=0

# case <want:accept|reject> <label> <body-text>
case_is() {
	local want="$1" label="$2" body="$3" got
	printf '%s\n' "$body" >"$tmp/body.md"
	if bash "$SCRIPT" body "$tmp/body.md" >/dev/null 2>&1; then got=accept; else got=reject; fi
	if [ "$got" = "$want" ]; then
		pass=$((pass + 1))
	else
		fail=$((fail + 1))
		echo "FAIL: $label — wanted $want, got $got" >&2
	fi
}

# --- Accepted: every trailer form this repository's history actually uses ------
case_is accept "plain model version" 'Text.

Assisted-by: Claude:claude-opus-5'
case_is accept "bracketed context suffix (iss-214)" 'Text.

Assisted-by: Claude:claude-opus-5[1m]'
case_is accept "bracketed, earlier model (iss-214)" 'Text.

Assisted-by: Claude:claude-opus-4-8[1m]'
case_is accept "dotted/dashed version" 'Text.

Assisted-by: Claude:claude-sonnet-5'
# The positive check is deliberately vendor-agnostic (iss-215): the convention is
# <Vendor>:<model-version>, with Claude an example rather than the literal.
case_is accept "another vendor" 'Text.

Assisted-by: OpenAI:gpt-5'

# --- Rejected -----------------------------------------------------------------
# Correct per iss-214, recorded so it is not re-raised as a defect: the
# convention requires a model VERSION, so a bare vendor is non-conformant.
case_is reject "vendor with no version" 'Text.

Assisted-by: Claude'
case_is reject "no trailer at all" 'Just prose, nothing else.'
case_is reject "tool footer, markdown link" 'Text.

🤖 Generated with [Some Tool](https://example.invalid)

Assisted-by: Claude:claude-opus-5'
case_is reject "tool footer, no emoji" 'Text.

Generated with [Some Tool](https://example.invalid)

Assisted-by: Claude:claude-opus-5'
case_is reject "tool footer, generated BY" 'Text.

Generated by [Some Tool](https://example.invalid)

Assisted-by: Claude:claude-opus-5'
# iss-262: the footer shape a hosted agent platform actually appends is WRAPPED IN
# MARKDOWN EMPHASIS. The first cut anchored on optional whitespace only, so the
# exact form that motivated this gate — a leading underscore — sailed through the
# body check. Found live on two pull requests whose failing leg was something else
# entirely, which is how it went unnoticed.
case_is reject "tool footer, italic underscore (iss-262)" 'Text.

_Generated by [Some Tool](https://example.invalid)_

Assisted-by: Claude:claude-opus-5'
case_is reject "tool footer, italic asterisk (iss-262)" 'Text.

*Generated with [Some Tool](https://example.invalid)*

Assisted-by: Claude:claude-opus-5'
case_is reject "tool footer, bold (iss-262)" 'Text.

**Generated with [Some Tool](https://example.invalid)**

Assisted-by: Claude:claude-opus-5'
case_is reject "tool footer, italic with emoji (iss-262)" 'Text.

_🤖 Generated with [Some Tool](https://example.invalid)_

Assisted-by: Claude:claude-opus-5'
case_is reject "tool footer, italic after a rule (iss-262)" 'Text.

---
_Generated by [Some Tool](https://example.invalid)_

Assisted-by: Claude:claude-opus-5'
# The emoji may sit OUTSIDE the emphasis run as readily as inside it, and
# bold-italic is three markers, not two. Both forms are ordinary markdown and both
# evaded the first cut of this widening — each is one character class away from
# the forms above, so pin them rather than wait to meet them in the wild.
case_is reject "tool footer, emoji outside the emphasis (iss-262)" 'Text.

🤖 _Generated with [Some Tool](https://example.invalid)_

Assisted-by: Claude:claude-opus-5'
case_is reject "tool footer, bold-italic asterisks (iss-262)" 'Text.

***Generated with [Some Tool](https://example.invalid)***

Assisted-by: Claude:claude-opus-5'
case_is reject "tool footer, bold-italic underscores (iss-262)" 'Text.

___Generated by [Some Tool](https://example.invalid)___

Assisted-by: Claude:claude-opus-5'
# The emphasis marker must be attached to the word, exactly as markdown reads it:
# `*text*` is emphasis, `* text` is a LIST ITEM. A bullet describing the banned
# footer is documentation, the same as the `-` bullet form the anchor already
# admits — widening to emphasis must not quietly start rejecting list items.
case_is accept "asterisk BULLET describing the footer (not emphasis)" '* Generated by [Some Tool](https://example.invalid) is the footer we refuse.

Assisted-by: Claude:claude-opus-5'
case_is accept "hyphen bullet describing the footer" '- Generated with [Some Tool](https://example.invalid) is refused.

Assisted-by: Claude:claude-opus-5'
# iss-215: the co-authorship ban must match the trailer KEY, not one vendor's
# name — an AI co-author line wearing another vendor's name was passing.
case_is reject "AI co-author, another vendor" 'Text.

Co-authored-by: ChatGPT <bot@openai.invalid>
Assisted-by: OpenAI:gpt-5'
case_is reject "AI co-author, this vendor" 'Text.

Co-Authored-By: Claude <noreply@anthropic.invalid>
Assisted-by: Claude:claude-opus-5'

# The gate must be writable-about. A footer occupies its own line; prose quoting
# the banned form mid-sentence is documentation, not a footer. Unanchored, the
# rule rejected the very commit that introduced it (and would reject this file,
# the CHANGELOG entry and the issue records).
case_is accept "prose quoting the banned footer" 'We ban the "Generated with [tool](url)" footer, and "Generated by [tool](url)" too.

Assisted-by: Claude:claude-opus-5'
case_is accept "prose quoting the co-author ban" 'The rule is that no Co-authored-by: line may name an AI. See AGENTS.md.

Assisted-by: Claude:claude-opus-5'

# --- Fenced code blocks are quoted material, not the document's own voice ------
# iss-268: mid-sentence prose was the ONLY way to document the banned shape, so a
# fenced example — the natural way to show a literal — was refused exactly as a
# real footer would be. This PR's own first description tripped it. A fenced block
# is quotation, so the rule reads both directions: a banned form inside one is an
# example, and the required trailer inside one is an example too (it cannot serve
# as the declaration).
case_is accept "banned footer inside a fenced block (iss-268)" 'The footer we refuse looks like this:

```
_Generated by [Some Tool](https://example.invalid)_
```

Assisted-by: Claude:claude-opus-5'
case_is accept "co-author ban inside a fenced block (iss-268)" 'Never write:

```
Co-authored-by: Claude <noreply@anthropic.invalid>
```

Assisted-by: Claude:claude-opus-5'
case_is accept "tilde fence (iss-268)" 'Shown with tildes:

~~~
Generated with [Some Tool](https://example.invalid)
~~~

Assisted-by: Claude:claude-opus-5'
case_is accept "fence indented up to three spaces (iss-268)" 'Indented example:

   ```
   _Generated by [Some Tool](https://example.invalid)_
   ```

Assisted-by: Claude:claude-opus-5'
# The trailer must be the document speaking. One that exists only as an example
# inside a fence is not a disclosure, so the body still has none.
case_is reject "trailer ONLY inside a fence is not a declaration (iss-268)" 'How to disclose:

```
Assisted-by: Claude:claude-opus-5
```'
# Stripping the quotation must not hide anything outside it.
case_is reject "real footer after a closed fence (iss-268)" 'An example:

```
some code
```

_Generated by [Some Tool](https://example.invalid)_

Assisted-by: Claude:claude-opus-5'
case_is reject "real footer before a closed fence (iss-268)" '_Generated by [Some Tool](https://example.invalid)_

```
some code
```

Assisted-by: Claude:claude-opus-5'
# An UNCLOSED fence fails closed. Markdown renders the rest of the document as
# code, so honouring it would let one stray fence line suppress every check below
# it — the cheapest possible bypass. An unbalanced document is quoted nowhere.
# The trailer sits BEFORE the stray fence and the footer after it, so honouring an
# unclosed fence would strip the footer and leave a compliant-looking body — the
# case had to be shaped this way to discriminate. Rejecting for a missing trailer
# would pass whether the fence was honoured or not, and prove nothing.
case_is reject "unclosed fence does not suppress the check (iss-268)" 'Assisted-by: Claude:claude-opus-5

Oops, never closed:

```
_Generated by [Some Tool](https://example.invalid)_
'
# A tab-indented or deeply-indented line is not a fence in markdown, so it is not
# quotation and the gate still applies — the conservative reading.
case_is reject "four-space indent is not a fence (iss-268)" 'Indented four:

    ```
    _Generated by [Some Tool](https://example.invalid)_
    ```

Assisted-by: Claude:claude-opus-5'

# --- Not a shell --------------------------------------------------------------
# The body is attacker-controlled text; it must never be evaluated.
case_is accept "body containing shell metacharacters" 'evil $(touch '"$tmp"'/PWNED) `id` ${IFS}

Assisted-by: Claude:claude-opus-5'
if [ -e "$tmp/PWNED" ]; then
	echo "FAIL: body containing shell metacharacters — the body was EXECUTED" >&2
	fail=$((fail + 1))
fi

# --- The git identity itself (commits mode) -----------------------------------
# The contributor graph is built from commit AUTHORSHIP plus Co-authored-by
# trailers, not from messages alone. A commit authored as
# `Claude <noreply@anthropic.com>` with a fully compliant message sailed through
# the message-only gate, put an AI at #2 in the contributor graph, and — because
# a squash merge auto-appends a Co-authored-by for any branch author who is not
# the PR author — inflated it again on every squash of that branch. These cases
# prove the commits half reads the identity, not only the message.
repo="$tmp/repo"
git init -q "$repo"
git -C "$repo" -c user.name=REPPL -c user.email=human@example.invalid \
	commit -q --allow-empty -m 'base'
base="$(git -C "$repo" rev-parse HEAD)"
SCRIPT_ABS="$(pwd)/$SCRIPT"

# commits_case <want> <label> — checks base..HEAD in the scratch repo, then resets.
commits_case() {
	local want="$1" label="$2" got
	if (cd "$repo" && bash "$SCRIPT_ABS" commits "$base" HEAD >/dev/null 2>&1); then
		got=accept
	else
		got=reject
	fi
	if [ "$got" = "$want" ]; then
		pass=$((pass + 1))
	else
		fail=$((fail + 1))
		echo "FAIL: $label — wanted $want, got $got" >&2
	fi
	git -C "$repo" reset -q --hard "$base"
}

# commit_as <author-name> <author-email> <committer-name> <committer-email> <msg>
commit_as() {
	GIT_AUTHOR_NAME="$1" GIT_AUTHOR_EMAIL="$2" \
		GIT_COMMITTER_NAME="$3" GIT_COMMITTER_EMAIL="$4" \
		git -C "$repo" commit -q --allow-empty -m "$5"
}

MSG_OK='Text.

Assisted-by: Claude:claude-opus-5'

commit_as REPPL human@example.invalid REPPL human@example.invalid "$MSG_OK"
commits_case accept "human identity, compliant message"

# The bf68242 case: identity is the AI, message is fully compliant.
commit_as Claude noreply@anthropic.com Claude noreply@anthropic.com "$MSG_OK"
commits_case reject "AI author and committer, compliant message"

commit_as REPPL human@example.invalid Claude noreply@anthropic.com "$MSG_OK"
commits_case reject "AI committer only, compliant message"

commit_as Claude claude@example.invalid REPPL human@example.invalid "$MSG_OK"
commits_case reject "AI author by name alone, compliant message"

# Vendor-agnostic, as with the co-authorship ban (iss-215).
commit_as ChatGPT bot@openai.com REPPL human@example.invalid "$MSG_OK"
commits_case reject "another vendor's AI author, compliant message"

# A human whose name merely CONTAINS an AI name is not an AI identity.
commit_as 'Claudette Martin' claudette@example.invalid 'Claudette Martin' claudette@example.invalid "$MSG_OK"
commits_case accept "human name containing an AI name"

# The bot exemption still holds: dependabot writes no trailer and stays exempt.
commit_as 'dependabot[bot]' '49699333+dependabot[bot]@users.noreply.github.com' \
	'GitHub' 'noreply@github.com' 'chore(deps): bump something'
commits_case accept "bot author without trailer (exemption)"

# --- The human-only declaration -----------------------------------------------
# A change no AI touched discloses that positively; silence stays refused,
# because an absent trailer and a forgotten one are indistinguishable.
case_is accept "human-only declaration" 'A change I wrote by hand.

Assisted-by: None'
case_is accept "human-only declaration, lower case" 'A change I wrote by hand.

Assisted-by: none'
case_is reject "still no trailer at all" 'A change with nothing disclosed.'
# The declaration is a closed value, not a free-text escape: anything else in
# the slot would reopen the omission it exists to close.
case_is reject "free-text escape is not a declaration" 'Text.

Assisted-by: n/a'
case_is reject "free-text escape (human)" 'Text.

Assisted-by: human'
case_is reject "None with trailing prose is not the declaration" 'Text.

Assisted-by: None really'
# The declaration never licenses the banned forms.
case_is reject "declaration alongside a co-authorship trailer" 'Text.

Assisted-by: None
Co-authored-by: Someone <someone@example.invalid>'
case_is reject "declaration alongside a generated-with footer" 'Text.

🤖 Generated with [Some Tool](https://example.invalid)

Assisted-by: None'

# A human-only COMMIT passes the commit check on the same terms.
commit_as REPPL human@example.invalid REPPL human@example.invalid 'docs: a hand-written change

Assisted-by: None'
commits_case accept "human-only commit declaration"

# An AI identity is still refused even when the message declares human-only —
# the identity fields are what the contributor graph reads.
commit_as Claude noreply@anthropic.com REPPL human@example.invalid 'docs: a change

Assisted-by: None'
commits_case reject "AI identity claiming human-only"

echo "check-attribution-cases: $pass passed, $fail failed"
[ "$fail" -eq 0 ]
