#!/usr/bin/env bash
# Test corpus for check-attribution.sh's body check.
#
# iss-214 asked for this specifically: the regex must be proven against the
# trailer forms ACTUALLY IN USE in this repository's history, not only against
# the happy path it was written from. `git log` over the record at the time of
# writing shows claude-fable-5 (256), claude-opus-4-8 (225), claude-opus-5 (123),
# claude-opus-5[1m] (33), claude-sonnet-5 (12) and claude-opus-4-8[1m] (5) — the
# bracketed context-window forms are ordinary history, and the first cut of the
# gate rejected every one of them.
#
# Run: bash scripts/check-attribution-cases.sh   (exit 0 all pass, 1 otherwise)
set -uo pipefail
cd "$(git rev-parse --show-toplevel)"

SCRIPT=scripts/check-attribution.sh
tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

pass=0
fail=0

# case <want:accept|reject> <label> <body-text>
case_is() {
	local want="$1" label="$2" body="$3" got
	printf '%s\n' "$body" >"$tmp/body.md"
	if bash "$SCRIPT" body "$tmp/body.md" >/dev/null 2>&1; then got=accept; else got=reject; fi
	if [ "$got" = "$want" ]; then
		pass=$((pass + 1))
	else
		fail=$((fail + 1))
		echo "FAIL: $label — wanted $want, got $got" >&2
	fi
}

# --- Accepted: every trailer form this repository's history actually uses ------
case_is accept "plain model version" 'Text.

Assisted-by: Claude:claude-opus-5'
case_is accept "bracketed context suffix (iss-214)" 'Text.

Assisted-by: Claude:claude-opus-5[1m]'
case_is accept "bracketed, earlier model (iss-214)" 'Text.

Assisted-by: Claude:claude-opus-4-8[1m]'
case_is accept "dotted/dashed version" 'Text.

Assisted-by: Claude:claude-sonnet-5'
# The positive check is deliberately vendor-agnostic (iss-215): the convention is
# <Vendor>:<model-version>, with Claude an example rather than the literal.
case_is accept "another vendor" 'Text.

Assisted-by: OpenAI:gpt-5'

# --- Rejected -----------------------------------------------------------------
# Correct per iss-214, recorded so it is not re-raised as a defect: the
# convention requires a model VERSION, so a bare vendor is non-conformant.
case_is reject "vendor with no version" 'Text.

Assisted-by: Claude'
case_is reject "no trailer at all" 'Just prose, nothing else.'
case_is reject "tool footer, markdown link" 'Text.

🤖 Generated with [Some Tool](https://example.invalid)

Assisted-by: Claude:claude-opus-5'
case_is reject "tool footer, no emoji" 'Text.

Generated with [Some Tool](https://example.invalid)

Assisted-by: Claude:claude-opus-5'
case_is reject "tool footer, generated BY" 'Text.

Generated by [Some Tool](https://example.invalid)

Assisted-by: Claude:claude-opus-5'
# iss-215: the co-authorship ban must match the trailer KEY, not one vendor's
# name — an AI co-author line wearing another vendor's name was passing.
case_is reject "AI co-author, another vendor" 'Text.

Co-authored-by: ChatGPT <bot@openai.invalid>
Assisted-by: OpenAI:gpt-5'
case_is reject "AI co-author, this vendor" 'Text.

Co-Authored-By: Claude <noreply@anthropic.invalid>
Assisted-by: Claude:claude-opus-5'

# The gate must be writable-about. A footer occupies its own line; prose quoting
# the banned form mid-sentence is documentation, not a footer. Unanchored, the
# rule rejected the very commit that introduced it (and would reject this file,
# the CHANGELOG entry and the issue records).
case_is accept "prose quoting the banned footer" 'We ban the "Generated with [tool](url)" footer, and "Generated by [tool](url)" too.

Assisted-by: Claude:claude-opus-5'
case_is accept "prose quoting the co-author ban" 'The rule is that no Co-authored-by: line may name an AI. See AGENTS.md.

Assisted-by: Claude:claude-opus-5'

# --- Not a shell --------------------------------------------------------------
# The body is attacker-controlled text; it must never be evaluated.
case_is accept "body containing shell metacharacters" 'evil $(touch '"$tmp"'/PWNED) `id` ${IFS}

Assisted-by: Claude:claude-opus-5'
if [ -e "$tmp/PWNED" ]; then
	echo "FAIL: body containing shell metacharacters — the body was EXECUTED" >&2
	fail=$((fail + 1))
fi

echo "check-attribution-cases: $pass passed, $fail failed"
[ "$fail" -eq 0 ]
