#!/usr/bin/env bash
# Deterministic gate for abcd's AI-attribution convention (AGENTS.md § Attribution,
# CONTRIBUTING.md): an AI-assisted commit message and an AI-assisted pull-request
# body each carry the kernel-format trailer
#
#   Assisted-by: Claude:<model-version>
#
# and never `Co-Authored-By:` for an AI, and never a tool's own "Generated with
# <tool>" footer.
#
# Stopgap: the convention has lived as prose in AGENTS.md and CONTRIBUTING.md
# since the beginning and drifted anyway — itd-91 records a reconciliation sweep
# across 78 pull requests after PR bodies picked up a tool's default footer. Prose
# is not the missing piece; a check that fails closed is. itd-91 owns the general
# version (a per-repo declared preference every surface reads); this enforces
# abcd's own answer until that lands.
#
# Usage:
#   check-attribution.sh commits <base-ref> <head-ref>   # every non-merge commit in the range
#   check-attribution.sh body <file>                     # a pull-request body on stdin-file
#
# Exit 0 clean, 1 a violation, 2 a usage/environment fault.
set -euo pipefail

# The sanctioned trailer. Kernel format: a `Key: value` line, value naming the
# assisting model. Anchored to line start so a mention inside prose is not a pass.
TRAILER_RE='^Assisted-by: [A-Za-z][A-Za-z0-9._-]*:[A-Za-z0-9._-]+$'

# Footers a tool emits by default. These name a tool outside the two credit
# surfaces AGENTS.md sanctions (the README badge and ACKNOWLEDGEMENTS.md), which
# is why they are refused here rather than merely discouraged.
GENERATED_RE='Generated with \[|🤖 Generated with|Co-authored-by: Claude|Co-Authored-By: Claude'

fail=0
note() { echo "  $1" >&2; }

usage() {
	echo "usage: check-attribution.sh commits <base-ref> <head-ref> | body <file>" >&2
	exit 2
}

# check_text applies both halves to one artefact: the banned footer must be
# absent, and the trailer must be present.
check_text() {
	local label="$1" text="$2"
	if printf '%s' "$text" | grep -Eq "$GENERATED_RE"; then
		echo "check-attribution: $label carries a tool's default attribution footer" >&2
		note "abcd uses the kernel trailer 'Assisted-by: Claude:<model-version>' as disclosure,"
		note "not authorship. 'Co-Authored-By:' asserts an authorship the tool does not hold and"
		note "inflates the contributor graph; a 'Generated with <tool>' footer names a tool outside"
		note "the credit surfaces AGENTS.md sanctions. Replace the footer with the trailer."
		fail=1
		return
	fi
	if ! printf '%s' "$text" | grep -Eq "$TRAILER_RE"; then
		echo "check-attribution: $label has no 'Assisted-by:' trailer" >&2
		note "Add a final line of the form: Assisted-by: Claude:claude-opus-5"
		note "(If this artefact had no AI assistance, say so in the PR and this gate can be"
		note "revisited — the convention is disclosure, and a human-only change has nothing to"
		note "disclose. Today the gate asks for the trailer on every non-bot contribution.)"
		fail=1
	fi
}

case "${1:-}" in
commits)
	[ $# -eq 3 ] || usage
	base="$2"
	head="$3"
	# --no-merges: a merge commit is generated by the forge, not authored here, and
	# carries no trailer of its own.
	range="$(git rev-list --no-merges "$base".."$head")"
	if [ -z "$range" ]; then
		echo "check-attribution: no non-merge commits in $base..$head — nothing to check"
		exit 0
	fi
	while IFS= read -r sha; do
		[ -n "$sha" ] || continue
		# A bot's commit is exempt: dependabot cannot write a trailer, and failing its
		# PRs would train the maintainer to discount a red gate on exactly the PRs where
		# a red gate most needs to be trusted.
		author_email="$(git show -s --format='%ae' "$sha")"
		case "$author_email" in
		*"[bot]@users.noreply.github.com" | *"@dependabot.com")
			continue
			;;
		esac
		check_text "commit ${sha:0:12} ($(git show -s --format='%s' "$sha" | cut -c1-50))" \
			"$(git show -s --format='%B' "$sha")"
	done <<<"$range"
	;;
body)
	[ $# -eq 2 ] || usage
	[ -f "$2" ] || {
		echo "check-attribution: no such file: $2" >&2
		exit 2
	}
	check_text "the pull-request body" "$(cat "$2")"
	;;
*)
	usage
	;;
esac

if [ "$fail" -ne 0 ]; then
	echo "check-attribution: FAILED — see AGENTS.md § Attribution and acknowledgements" >&2
	exit 1
fi
echo "check-attribution: clean"
