// Code generated by identitygen; DO NOT EDIT.
// Regenerate with: go generate ./internal/surface/cli
// Source of truth: the canonical identity block (itd-102); the drift test
// TestBakedIdentityInSync holds this file to it byte-for-byte.

package cli

const (
	bakedTitle   = "abcd — Agent-Based Configuration for Development"
	bakedTagline = "For people who know what they want to build and need help shipping it."
)
